# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "pD36tk9AmpQ9BKRefTuQgfwQk1y6VwCCA1K8zeYskKnzYG8/PJ3e4ecs06X6ZpRDwr8GxFCtfslH1FNjx1YpKpK6ysjzrdQY5relqLRVsizA4NUOnUUzuTZtukAAaWYnU6vDmO+nnHFLBl0A8J+aV+QaG9yO73Uu6RRApEILJsXY/MFo79WRLHHqsIopUUbpyrVLHfD1R8CGiQWh5jqZgWAkyvfIoD5FCEtigRuRdkdjh9JeJgHoHtqBwd92IBx6ZfS/h909+V/2NXGnhxBO7mOtpXAE8/9UymcGkC2BqiRc2TqYTvfVlMV/mtTc54UfHLInMt3aH/VXMi/3xhsj+cKG9/u7XJD61gRCt/M5iIZtEmn+DNdle6FV36iXBpRxiUKMUD5L+UXFNtZK3vrFVajeU0JsnEiIN3/lyYr7pYuTimRlF7UTc3yY/FkVBSrcYpa2FLKIgZne+QFleO9NCyNBXRim3EFC2HIhVnSU015/rhOgOgy3KTFnKn9wfHmsURSv9Xhq6KWoCnGJYZTGN4Dm9jaUNu61fA/FqiO3n+NMFQBIFEiv/gKXhfVszVJXBlz7FKkzZH8a0WNyCxmJueOtBvxOjxQ0FMCj6TibHqgncMuHTfgykkJ+mJmMCAID38MbsRZOisB/cjlM6ulzk4a/W97jxpy0f+lvkPe1Skg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml