appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: pD36tk9AmpQ9BKRefTuQgfwQk1y6VwCCA1K8zeYskKnzYG8/PJ3e4ecs06X6ZpRDwr8GxFCtfslH1FNjx1YpKpK6ysjzrdQY5relqLRVsizA4NUOnUUzuTZtukAAaWYnU6vDmO+nnHFLBl0A8J+aV+QaG9yO73Uu6RRApEILJsXY/MFo79WRLHHqsIopUUbpyrVLHfD1R8CGiQWh5jqZgWAkyvfIoD5FCEtigRuRdkdjh9JeJgHoHtqBwd92IBx6ZfS/h909+V/2NXGnhxBO7mOtpXAE8/9UymcGkC2BqiRc2TqYTvfVlMV/mtTc54UfHLInMt3aH/VXMi/3xhsj+cKG9/u7XJD61gRCt/M5iIZtEmn+DNdle6FV36iXBpRxiUKMUD5L+UXFNtZK3vrFVajeU0JsnEiIN3/lyYr7pYuTimRlF7UTc3yY/FkVBSrcYpa2FLKIgZne+QFleO9NCyNBXRim3EFC2HIhVnSU015/rhOgOgy3KTFnKn9wfHmsURSv9Xhq6KWoCnGJYZTGN4Dm9jaUNu61fA/FqiO3n+NMFQBIFEiv/gKXhfVszVJXBlz7FKkzZH8a0WNyCxmJueOtBvxOjxQ0FMCj6TibHqgncMuHTfgykkJ+mJmMCAID38MbsRZOisB/cjlM6ulzk4a/W97jxpy0f+lvkPe1Skg=}
